config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "devices#index"
  
  resources :devices do
    resources :notifications do
      resources :subscriptions, only: [:create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
  has_and_belongs_to_many :users
  has_one :notification, dependent: :destroy
  validates :thing_name, presence: true
  after_find :get_shadow
  attr_accessor :temperature, :timestamp, :rule
  
  def get_shadow
    begin
      resp             = DevicesHelper::DATA_PLANE.get_thing_shadow(thing_name: self.thing_name)
      shadow           = JSON.parse(resp.payload.string)
      self.temperature = shadow['state']['reported']['temp']
      self.timestamp   = shadow['metadata']['reported']['temp']['timestamp']
    rescue StandardError => e
      puts "Rescued #{e.inspect}"
    end
  end
  
  def rule_params
    {
      rule_name: rule_name,
      topic_rule_payload: {
        sql: build_sql,
        actions: [{
          sns: {
            target_arn: notification.arn,
            role_arn: ENV['SNS_ROLE_ARN'],
            message_format: "RAW",
          }
        }]
      }
    }
  end
  
  def create_rule
    begin
      DevicesHelper::IOT_CLIENT.create_topic_rule(rule_params)
    rescue StandardError => e
      puts "Rescued #{e.inspect}"
      false
    end
  end
  
  def update_rule
    begin
      DevicesHelper::IOT_CLIENT.replace_topic_rule(rule_params)
    rescue StandardError => e
      puts "Rescued #{e.inspect}"
    end
  end
  
  def build_sql
    topic     = "$aws/things/#{thing_name}/shadow/update"
    attribute = "state.reported.temp"
    <<-SQL
      SELECT VALUE #{attribute}
      FROM '#{topic}'
      WHERE #{attribute} <= #{notification.min}
      OR #{attribute} >= #{notification.max}
    SQL
  end
  
  def rule
    @rule ||= get_rule
  end

  def get_rule
    begin
      resp = DevicesHelper::IOT_CLIENT.get_topic_rule(rule_name: rule_name)
      resp.rule
    rescue StandardError => e
      puts "Rescued #{e.inspect}"
    end
  end
  
  def rule_name
    "#{thing_name}_temp_threshold"
  end
  
  def last_updated
    t = Time.at(timestamp).in_time_zone("Pacific Time (US & Canada)")
    t.strftime("%A, %B %d %Y, %I:%M %p #{t.zone}")
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :device
  validates :arn, :min, :max, presence: true
  validate :min_cannot_be_greater_than_max
  after_update :update_rule
  attr_accessor :numbers, :subscriptions
  
  def generate!(name = "TempMonitor")
    topic = DevicesHelper.create_sns_topic(device.thing_name, name)
    numbers.each { |n| topic.subscribe(protocol: 'sms', endpoint: n) }
    self.update(arn: topic.arn)
  end
  
  def topic
    Aws::SNS::Topic.new(arn)
  end
  
  def update_rule
    self.device.update_rule
  end
  
  def subscriptions
    @subscriptions ||= get_subscriptions
  end
  
  def get_subscriptions
    topic.subscriptions
  end
  
  def add_subscription(number)
    topic.subscribe(protocol: 'sms', endpoint: number)
    subscriptions = get_subscriptions
  end
  
  def remove_subscription(arn)
    subscription = subscriptions.find { |s| s.arn === arn }
    subscription.delete()
    subscriptions = get_subscriptions
  end
  
  def min_cannot_be_greater_than_max
    return unless min && max
    if min >= max
      errors.add(:threshold, "Min must be less than Max")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_and_belongs_to_many :devices
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, :with => :render_404

  def render_404
    render :file => "#{Rails.root}/public/404.html", :status => 404
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    device = Device.find_or_create_by(device_params)
    device.users << current_user
    flash[:notice] = "Successfully added device!"
    redirect_to action: "index"
  end

  def index
    @devices = current_user.devices   
  end
  
  def show
    @device = Device.find(params[:id])
    @notification = @device.notification || Notification.new(device: @device)
  end
  
  private
  def device_params
    params.require(:device).permit(:thing_name)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController  
  def create
    @device = Device.find(params[:device_id])
    @notification = Notification.new(notification_params.merge(device: @device))
    @notification.numbers.reject(&:blank?)
      .map! { |n| n.gsub("-", "").prepend("1") }
    if @notification.generate! && @device.create_rule
      flash[:notice] = "Notification created successfully"
    else
      flash[:alert] = @notification.errors.full_messages.to_sentence
    end
    redirect_to @device
  end
  
  def update
    @notification = Notification.find(params[:id])
    if @notification.update(notification_params) && 
      flash[:notice] = "Notification updated successfully"
    else
      flash[:alert] = @notification.errors.full_messages.to_sentence
    end
    redirect_to @notification.device
  end
  
  private
  def notification_params
    params.require(:notification).permit(:max, :min, numbers: [])
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_objects

  def create
    number = params[:number].gsub("-", "").prepend("1")
    if @notification.add_subscription(number)
      flash[:notice] = "Subscription Added"
    else
      flash[:alert] = "Something went wrong"
    end
    redirect_to @device
  end
  
  def destroy
    if @notification.remove_subscription(params[:id])
      flash[:notice] = "Subscription Removed"
    else
      flash[:alert] = "Something went wrong"
    end
    redirect_to @device
  end
  
  private
  def set_objects
    @device       = Device.find(params[:device_id])
    @notification = Notification.find(params[:notification_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
  DATA_PLANE = Aws::IoTDataPlane::Client.new(endpoint: ENV['ENDPOINT'], region: ENV['AWS_REGION'])
  IOT_CLIENT = Aws::IoT::Client.new

  def self.create_sns_topic(thing_name, display)
    sns    = Aws::SNS::Resource.new
    name   = "#{thing_name}TempWarning"
    params = { name: name, attributes: { DisplayName: display } }
    sns.create_topic(params)
  end
end

app/views/devices/_add_device.html.erb
<section class="d-flex flex-column align-items-center font-weight-lighter m-5">
  <h5 class="font-weight-lighter">Add a Device</h5>
  <%= simple_form_for Device.new do |f| %>
    <%= f.input :thing_name, required: true %>
    <%= f.button :submit, "Add Device", class: "btn btn-primary" %>
  <% end %>  
</section>

app/views/devices/index.html.erb
<h1 class="font-weight-lighter text-center">Devices</h1>
<section class="d-flex justify-content-center">
  <% if @devices.blank? %>
    <%= render "devices/add_device" %>
  <% else %>
    <% @devices.each do |device| %>
      <section class="card">
        <section class="card-body">
          <h3 class="card-title"><%= device.temperature %></h3>
          <h5 class="card-subtitle text-muted"><%= device.thing_name %></h5>
          <div><%= link_to 'Details', device_path(device), class: "card-link" %></div>
        </section>
      </section>
    <% end %>
  <% end %>
</section>

app/views/devices/show.html.erb
<!-- Temperature -->
<section class="d-flex flex-column align-items-center font-weight-lighter mt-4">
  <!-- Temperature Reading -->
  <section>
    <span id="temperature"><%= @device.temperature %><span>
    <span id="units">&deg;</span>
  </section>
  <!-- Last Updated Timestamp -->
  <section class="p-2">
     <span id="timestamp"><%= @device.last_updated %></span>
  </section>
</section>

<!-- Notifications -->
<%= render "notifications/show" %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Temperature Monitor", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if current_user %>
      <li class="nav-item"><%= link_to "Devices", devices_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Settings", edit_user_registration_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Log out", destroy_user_session_path, method: 'delete', class: "nav-link" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Register", new_user_registration_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_notification.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info center-text" role="alert">
    <%= flash[:notice].html_safe %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger center-text" role="alert">
    <%= flash[:alert].html_safe %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TempMonitor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
    <link rel="apple-touch-icon" type="image/png" href="apple-touch-icon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid p-0">
    <%= render "layouts/navigation" %>
    <%= render "layouts/notification" %>
    <main class="d-flex flex-column align-items-center">
      <%= yield %>
    </main>
  </body>
</html>

app/views/notifications/_edit.html.erb
<section class="m-2">
  <%= simple_form_for @notification, url: device_notification_path(@device, @notification), method: :patch do |f| %>
    <%= f.input :min, required: true %>
    <%= f.input :max, required: true %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</section>

app/views/notifications/_new.html.erb
<h3 class="font-weight-lighter">Create a Notification</h3>
<%= simple_form_for Notification.new(device: @device), url: device_notifications_path(@device), method: :post do |f| %>
  <%= f.input :min, required: true %>
  <%= f.input :max, required: true %>
  <div id="numbers">
    <header class="m-1">Phone Numbers to Notify</header>
    <div class="number-field">
      <%= f.input_field :numbers, as: :array, label: false, required: true %>
      <span class="tag-remove"></span>
    </div>
  </div>
  <button id="add-phone-button" class="btn btn-link">Add another phone number</button>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/notifications/_new_subscription.html.erb
<%= form_for @notification, url: device_notification_subscriptions_path(@device, @notification), method: :post do |f| %>
  <%= f.label "Phone Number" %>
  <%= telephone_field_tag :number, nil, required: true %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/notifications/_show.html.erb
<section class="d-flex flex-column align-items-center font-weight-lighter m-4">
  <% unless @device.notification.id then %>
    <%= render "notifications/new" %>
  <% else %>
    <!-- Notifications -->
    <header id="notifications">Notifications</header>
    
    <section class="d-flex flex-column align-items-center m-3">
      <header class="m-1">Temperature Threshold</header>
      <%= render "notifications/edit" %>
    </section>
    
    <!-- Subscribed Phone Numbers -->
    <section class="d-flex flex-column align-items-center">
      <header class="m-1">Subscribed Numbers</header>    
      <%= render "notifications/subscriptions" %>
      <%= render "notifications/new_subscription" %>
    </section>
  <% end %>
</section>

app/views/notifications/_subscriptions.html.erb
<% if @device.notification.subscriptions.any? %>
  <ol>
    <% @notification.subscriptions.each do |s| %>
      <li class="m-2">
        <span><%= s.data.attributes["Endpoint"] %></span>
        <%= link_to 'Delete',
            device_notification_subscription_path(@device, @notification, s.data.attributes["SubscriptionArn"]),
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
      </li>
    <% end %>
  </ol>
<% end %>
  